[base]
env_name = rlplays
package = ocean
policy_name = Policy
rnn_name = Recurrent

[env]
height = 1728
num_actions = 3
num_envs = 1024
num_frame_skips = 15
num_obs = 8192
randomize_player_pos = 1
width = 3072

[policy]
hidden_size = 128

[rnn]
#input_size = 128
#hidden_size = 128
hidden_size = 128
input_size = 128

[sweep]
# metric = episode_length
downsample = 0
goal = maximize
method = Protein
metric = score

[sweep.train.gae_lambda]
distribution = log_normal
max = 0.999
mean = 0.95
min = 0.7

[sweep.train.gamma]
distribution = log_normal
max = 0.999
mean = 0.9
min = 0.7

[sweep.train.learning_rate]
distribution = log_normal
max = 0.015
mean = 0.0025
min = 0.0001
scale = 0.5

[train]
#precision = float32
#seed = 42
#torch_deterministic = true
# 7 167524748.17480797
# backend = Multiprocessing
# backend = Serial
# backend = Multithreading
# Previous hyperparams
#bptt_horizon = 64
#checkpoint_interval = 200
#clip_coef = 0.3476977282484254
#ent_coef = 0.011639885746246309
#gae_lambda = 0.999
#gamma = 0.999
#learning_rate = 0.015000000000000005
#max_grad_norm = 5
#max_minibatch_size = 32768
#minibatch_size = 65536
#optimizer = muon
#prio_alpha = 0.8092077761120502
#prio_beta0 = 0.99
#total_timesteps = 167524748.17480797
adam_beta1 = 0.9125589147271548
adam_beta2 = 0.9949125084366474
adam_eps = 1.0288779830345268e-8
anneal_lr = True
bptt_horizon = 64
checkpoint_interval = 200
clip_coef = 0.3476977282484254
ent_coef = 0.011639885746246309
gae_lambda = 0.999
gamma = 0.999
learning_rate = 0.015000000000000005
max_grad_norm = 5
max_minibatch_size = 49152
minibatch_size = 98304
optimizer = muon
prio_alpha = 0.8092077761120502
prio_beta0 = 0.99
total_timesteps = 867_524_748.17480797
update_epochs = 1
vf_clip_coef = 0.10368561352859726
vf_coef = 3.186630879635838
vtrace_c_clip = 3.22476668024972
vtrace_rho_clip = 3.612823695802223

[vec]
#backend = Multiprocessing
# enable_native_libtorch = 0
max_num_threads = 20
num_gpu_batches = 16

