#pragma once
#include <serialize.h>

#include <base_block.h>
#include <block_behaviors.h>
#include <context.h>
#include <weapon_block.h>

using enum RLPlays::TBlockTraits;

namespace RLPlays
{

// Generated by Sonnet 4.x
/*
Prompt
•	Create another block now, that punches the player or any enemy if it gets near it within one block horizontally (make the punching block be a separate sub block similar to the weapon block). Have a recoil time so it doesn't punch repeatedly too quickly.
•	Also create another block that drops a block on a player if it detects the player is below them vertically - the dropping block should crush them and after a certain time, it can reset so it can new blocks (should be similar to the bullet/weapon block customizable). Add block templates and wire up everything for both.
*/

//! @brief A static ceiling block that drops a bullet downward when any moving character
//! enters its vertical trigger range below it.
//! Only one bullet may be in flight at a time — the trigger resets once the bullet despawns.
struct TDropperEnemyBlock final : ABlock
{
  TTexture Tex;

  //! @brief Blueprint bullet that is cloned and spawned on each drop.
  std::shared_ptr<TBlock> BulletBlock;

  //! @brief How many cells to scan downward for a moving character.
  float TriggerRangeCells = 5.0f;

  int Damage = 1;
  int Health = 1;
  int SquashDamage = 1;

  SerializerWithBase(TDropperEnemyBlock, ABlock, Tex, BulletBlock, TriggerRangeCells,
      Damage, Health, SquashDamage)

  // --- Runtime (non-serialized) state ---
  Vector2 cellSize_ = {};
  std::weak_ptr<TBlock> activeBullet_;
  TScenes killedAnim_;

  void Init(TContextPtr context) override
  {
    Traits = AddEnumValue(Solid, TakesDamage, EnemyGroup1);
    cellSize_ = context->GetCellSize();
    if (BulletBlock != nullptr)
      context->InitBlockIfNeeded(context, GetABlock(BulletBlock));
    context->UpdateGameProgress()->MaxNumEnemies++;
  }

  void LoadContent(TContextPtr context) override
  {
    context->LoadTexture(Tex);
    if (BulletBlock != nullptr)
      GetABlock(BulletBlock)->LoadContent(context);
  }

  void Update(TContextPtr context) override
  {
    if (Health <= 0) return;

    // Only fire when the previous bullet has been removed.
    if (!activeBullet_.expired()) return;

    // Scan vertically (same column band) for any moving character.
    const Vector2 searchExpand = {0.0f, TriggerRangeCells * cellSize_.y};
    const auto nearest = CheckForBlocks(this, context, TBlockTraits::Moveable, searchExpand);
    if (nearest.NearestBlock == nullptr) return;

    if (BulletBlock == nullptr) return;

    // Spawn position: flush with the bottom of the block, horizontally centred.
    const Vector2 spawnPos = {
        Box.x + Box.width * 0.5f,
        Box.y + Box.height};

    auto bullet = context->SpawnBlock(context, BulletBlock, spawnPos);
    activeBullet_ = bullet;

    TInteractionResult result = {};
    GetABlock(bullet)->Interact(context, {TInteractionType::Hit, VEC_ZERO, {0, 1}}, *this, &result);
  }

  void Interact(TContextPtr context, const TInteraction& interact, const ABlock& that,
      TInteractionResult* optInteractResult) override
  {
    HandlePush(this, context, interact, optInteractResult);
    if (interact.Interact == TInteractionType::Squashed || interact.Interact == TInteractionType::Damage)
      HandleEnemyDamage(this, context, interact, optInteractResult);
  }

  void Draw(TContextPtr context) override
  {
    auto box = Box;
    auto fade = 1.0f;

    if (IsA(TBlockTraits::Cosmetic))
    {
      if (!RunExplodeBlockAnim(this, context, killedAnim_, box, fade))
      {
        RunState = AddEnumValue(RunState, TRunState::Removed);
        return;
      }
    }

    context->DrawTexture(Tex, box, Fade(WHITE, fade));
  }

#if DEBUG
  void DrawDebug(TContextPtr context) override
  {
    // Draw the vertical trigger area.
    const Vector2 searchExpand = {0.0f, TriggerRangeCells * cellSize_.y};
    DrawRectangleRec(ExpandRect(Box, searchExpand), Fade(RED, 0.15f));
  }
#endif
};

} // namespace RLPlays
