#pragma once
#include <serialize.h>

#include <base_block.h>
#include <block_behaviors.h>
#include <context.h>

using enum RLPlays::TBlockTraits;

namespace RLPlays
{
// Generated by Sonnet 4.x
/*
Prompt
•	Create another block now, that punches the player or any enemy if it gets near it within one block horizontally (make the punching block be a separate sub block similar to the weapon block). Have a recoil time so it doesn't punch repeatedly too quickly.
•	Also create another block that drops a block on a player if it detects the player is below them vertically - the dropping block should crush them and after a certain time, it can reset so it can new blocks (should be similar to the bullet/weapon block customizable). Add block templates and wire up everything for both.
*/

enum TPunchState : uint8_t
{
  PunchIdle   = 0,
  PunchActive = 1,
  PunchDone   = 2
};

//! @brief A brief melee hitbox spawned by TPunchingEnemyBlock.
//! Exists for a short duration, deals Damage to every hostile block it overlaps, then despawns.
//! Carries EnemyGroup1 so it never hits blocks of the same group (including its parent).
struct TPunchBlock final : ABlock
{
  TTexture Tex;
  //! @brief How long the hitbox stays visible before despawning.
  TCountdownTimer Duration = {NanosFromMillis(200)};
  int Damage = 1;

  SerializerWithBase(TPunchBlock, ABlock, Tex, Duration, Damage)

  // --- Runtime (non-serialized) state ---
  TPunchState state_ = PunchIdle;
  Vector2 facing_ = {1, 0};

  void Init(TContextPtr context) override
  {
    // EnemyGroup1 ensures MaskTraits() check skips the parent punching block.
    Traits = AddEnumValue(CauseDamage, Spawnable, EnemyGroup1);
    RunState = AddEnumValue(RunState, TRunState::Invisible);
    state_ = PunchIdle;
  }

  void LoadContent(TContextPtr context) override
  {
    if (!Tex.Filename.empty())
      context->LoadTexture(Tex);
  }

  void Interact(TContextPtr context, const TInteraction& interact, const ABlock& that,
      TInteractionResult* optInteractResult) override
  {
    if (interact.Interact != TInteractionType::Hit) return;
    RunState = RemoveEnumValue(RunState, TRunState::Invisible);
    facing_ = interact.Dir;
    // When facing left, shift the hitbox so it sits to the left of the spawn point.
    if (facing_.x < 0)
      context->MoveBlockBy(this, {-Box.width, 0});
    state_ = PunchActive;
    Duration.Start();
  }

  void Update(TContextPtr context) override
  {
    if (state_ == PunchIdle) return;

    if (state_ == PunchActive)
    {
      Duration.TickTimerPerFrame(context);

      auto& grid = context->Grid();
      grid->FindNeighbors(this, [&](TGridBlockInfo& neighbors) -> bool
      {
        auto* collider = neighbors.Neighbor;
        // Only hit blocks from a different group (players, cross-group enemies).
        if (!collider->IsA(TakesDamage)) return true;
        // Skip blocks in the same enemy group (avoids hitting the parent punching block).
        if (collider->MaskTraits(EnemyGroups) == this->MaskTraits(EnemyGroups)) return true;
        const auto hit = neighbors.CheckCollision(Box, {facing_.x, 0}, collider);
        if (!IsZeroVec(hit))
          collider->Interact(context, {TInteractionType::Damage, VEC_ZERO, facing_, Damage}, *this, nullptr);
        return true;
      }, {.allowedTraits = TakesDamage});

      if (!Duration.IsRunning())
        state_ = PunchDone;
    }

    if (state_ == PunchDone)
    {
      context->RemoveSpawnedBlock(*this);
      state_ = PunchIdle;
    }
  }

  void Draw(TContextPtr context) override
  {
    if (Tex.Filename.empty()) return;
    context->DrawTexture(Tex, facing_.x >= 0 ? Box : RectXInvert(Box), Fade(WHITE, 0.6f));
  }
};

//! @brief A static block that throws a melee punch at the first moving character that steps
//! within TriggerRangeCells horizontally. A RecoilTime prevents consecutive hits.
//! The punch sub-block is a separate blueprint, customisable just like TWeaponBlock's bullet.
struct TPunchingEnemyBlock final : ABlock
{
  TTexture Tex;
  //! @brief Blueprint punch-hitbox block cloned on each punch.
  std::shared_ptr<TBlock> PunchBlock;
  //! @brief Cells to scan to each side for a trigger (default: 1 = one block away).
  float TriggerRangeCells = 1.0f;
  //! @brief Cooldown between successive punches.
  TCountdownTimer RecoilTime = {NanosFromMillis(800)};
  int Health = 1;
  int SquashDamage = 1;
  Vector2 FacingDir = {1, 0};

  SerializerWithBase(TPunchingEnemyBlock, ABlock, Tex, PunchBlock, TriggerRangeCells,
      RecoilTime, Health, SquashDamage, FacingDir)

  // --- Runtime (non-serialized) state ---
  Vector2 cellSize_ = {};
  std::weak_ptr<TBlock> activePunch_;
  TScenes killedAnim_;

  void Init(TContextPtr context) override
  {
    Traits = AddEnumValue(Solid, TakesDamage, EnemyGroup1);
    cellSize_ = context->GetCellSize();
    if (PunchBlock != nullptr)
      context->InitBlockIfNeeded(context, GetABlock(PunchBlock));
    context->UpdateGameProgress()->MaxNumEnemies++;
  }

  void LoadContent(TContextPtr context) override
  {
    context->LoadTexture(Tex);
    if (PunchBlock != nullptr)
      GetABlock(PunchBlock)->LoadContent(context);
  }

  void Update(TContextPtr context) override
  {
    if (Health <= 0) return;

    RecoilTime.TickTimerPerFrame(context);

    // Block until both the active punch despawns AND the recoil period ends.
    if (RecoilTime.IsRunning() || !activePunch_.expired()) return;

    // Scan one cell to each side for any moving character.
    const Vector2 searchExpand = {TriggerRangeCells * cellSize_.x, 0.0f};
    const auto nearest = CheckForBlocks(this, context, TBlockTraits::Moveable, searchExpand);
    if (nearest.NearestBlock == nullptr) return;

    // Face toward the detected character.
    const auto myCenter = RectCenter(Box);
    FacingDir.x = (nearest.NearestPos.x >= myCenter.x) ? 1.0f : -1.0f;

    if (PunchBlock == nullptr) return;

    // Spawn hitbox flush with the facing side of this block, vertically centred.
    const Vector2 spawnPos = {
        FacingDir.x >= 0 ? (Box.x + Box.width) : Box.x,
        Box.y + Box.height * 0.5f};

    auto punch = context->SpawnBlock(context, PunchBlock, spawnPos);
    activePunch_ = punch;

    TInteractionResult result = {};
    GetABlock(punch)->Interact(context, {TInteractionType::Hit, VEC_ZERO, FacingDir}, *this, &result);
    RecoilTime.Start();
  }

  void Interact(TContextPtr context, const TInteraction& interact, const ABlock& that,
      TInteractionResult* optInteractResult) override
  {
    HandlePush(this, context, interact, optInteractResult);
    if (interact.Interact == TInteractionType::Squashed || interact.Interact == TInteractionType::Damage)
      HandleEnemyDamage(this, context, interact, optInteractResult);
  }

  void Draw(TContextPtr context) override
  {
    auto box = Box;
    auto fade = 1.0f;

    if (IsA(TBlockTraits::Cosmetic))
    {
      if (!RunExplodeBlockAnim(this, context, killedAnim_, box, fade))
      {
        RunState = AddEnumValue(RunState, TRunState::Removed);
        return;
      }
    }

    context->DrawTexture(Tex, FacingDir.x >= 0 ? box : RectXInvert(box), Fade(WHITE, fade));
  }

#if DEBUG
  void DrawDebug(TContextPtr context) override
  {
    const Vector2 searchExpand = {TriggerRangeCells * cellSize_.x, 0.0f};
    DrawRectangleRec(ExpandRect(Box, searchExpand), Fade(BLUE, 0.15f));
  }
#endif

#if RLPLAYS_EDITOR
  void EditorEnsureMirror(const std::shared_ptr<TEditorData>& editorData, TContextPtr context,
      const TBlock& thatBlock) override
  {
    FacingDir.x = -FacingDir.x;
  }
#endif
};

} // namespace RLPlays
