#pragma once
#include <serialize.h>

#include <base_block.h>
#include <block_behaviors.h>
#include <context.h>
#include <weapon_block.h>

using enum RLPlays::TBlockTraits;

namespace RLPlays
{
// Generated by Sonnet 4.x:
/*
Prompt:
Create a new block:
•	It's a static block that shoots a projectile horizontally if the player (or any moving character) triggers it within X blocks horizontally.
•	The projectile should be a bullet similar to how the PlayerBlock's bullet works
•	Once the projectile hits or goes outside the bounds, then the trigger can restart.
*/



//! @brief A static turret-like enemy that fires a horizontal bullet when any moving character
//! (player or enemy) enters its horizontal trigger range.
//! Only one bullet may be in flight at a time — the trigger resets once the bullet hits
//! something or travels out of range (times out).
struct TShooterEnemyBlock final : ABlock
{
  TTexture Tex;

  //! @brief Blueprint bullet that is cloned and spawned on each shot.
  std::shared_ptr<TBlock> BulletBlock;

  //! @brief How many cells to scan to each side for a moving character.
  float TriggerRangeCells = 5.0f;

  int Damage = 1;
  int Health = 1;
  int SquashDamage = 1;
  Vector2 FacingDir = {1, 0};

  SerializerWithBase(TShooterEnemyBlock, ABlock, Tex, BulletBlock, TriggerRangeCells,
      Damage, Health, SquashDamage, FacingDir)

  // --- Runtime (non-serialized) state ---
  Vector2 cellSize_ = {};
  std::weak_ptr<TBlock> activeBullet_;
  TScenes killedAnim_;

  void Init(TContextPtr context) override
  {
    Traits = AddEnumValue(Solid, TakesDamage, EnemyGroup1);
    cellSize_ = context->GetCellSize();
    if (BulletBlock != nullptr)
      context->InitBlockIfNeeded(context, GetABlock(BulletBlock));
    context->UpdateGameProgress()->MaxNumEnemies++;
  }

  void LoadContent(TContextPtr context) override
  {
    context->LoadTexture(Tex);
    if (BulletBlock != nullptr)
      GetABlock(BulletBlock)->LoadContent(context);
  }

  void Update(TContextPtr context) override
  {
    if (Health <= 0) return;

    // Only fire when the previous bullet has been removed.
    if (!activeBullet_.expired()) return;

    // Scan horizontally (same height band) for any moving character.
    const Vector2 searchExpand = {TriggerRangeCells * cellSize_.x, 0.0f};
    const auto nearest = CheckForBlocks(this, context, TBlockTraits::Moveable, searchExpand);
    if (nearest.NearestBlock == nullptr) return;

    // Aim toward the detected character.
    const auto myCenter = RectCenter(Box);
    FacingDir.x = (nearest.NearestPos.x >= myCenter.x) ? 1.0f : -1.0f;

    if (BulletBlock == nullptr) return;

    // Spawn position: flush with the facing side of the block, vertically centred.
    const Vector2 spawnPos = {
        FacingDir.x >= 0 ? (Box.x + Box.width) : Box.x,
        Box.y + Box.height * 0.5f};

    auto bullet = context->SpawnBlock(context, BulletBlock, spawnPos);
    activeBullet_ = bullet;

    TInteractionResult result = {};
    GetABlock(bullet)->Interact(context, {TInteractionType::Hit, VEC_ZERO, FacingDir}, *this, &result);
  }

  void Interact(TContextPtr context, const TInteraction& interact, const ABlock& that,
      TInteractionResult* optInteractResult) override
  {
    HandlePush(this, context, interact, optInteractResult);
    if (interact.Interact == TInteractionType::Squashed || interact.Interact == TInteractionType::Damage)
      HandleEnemyDamage(this, context, interact, optInteractResult);
  }

  void Draw(TContextPtr context) override
  {
    auto box = Box;
    auto fade = 1.0f;

    if (IsA(TBlockTraits::Cosmetic))
    {
      if (!RunExplodeBlockAnim(this, context, killedAnim_, box, fade))
      {
        RunState = AddEnumValue(RunState, TRunState::Removed);
        return;
      }
    }

    context->DrawTexture(Tex, FacingDir.x >= 0 ? box : RectXInvert(box), Fade(WHITE, fade));
  }

#if DEBUG
  void DrawDebug(TContextPtr context) override
  {
    // Draw the horizontal trigger area.
    const Vector2 searchExpand = {TriggerRangeCells * cellSize_.x, 0.0f};
    DrawRectangleRec(ExpandRect(Box, searchExpand), Fade(ORANGE, 0.15f));
  }
#endif

#if RLPLAYS_EDITOR
  void EditorEnsureMirror(const std::shared_ptr<TEditorData>& editorData, TContextPtr context,
      const TBlock& thatBlock) override
  {
    FacingDir.x = -FacingDir.x;
  }
#endif
};
} // namespace RLPlays
